config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'public_recipes#index'
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end
  resources :public_recipes, only: [:index]
  resources :general_shopping_lists, only: [:index], path: :general_shopping_list
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, Recipe, user_id: user.id

    can :manage, Recipe, user_id: user.id unless user.nil?
    can :manage, Food, user_id: user.id unless user.nil?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
  has_many :inventories, through: :inventory_foods, dependent: :destroy
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :measurement_unit, presence: true
  validates :price, presence: true, comparison: { greater_than_or_equal_to: 0 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
  has_many :foods, through: :inventory_foods, dependent: :destroy
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :food
  belongs_to :inventory
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :preparation_time, presence: true, length: { maximum: 10 }
  validates :cooking_time, presence: true, length: { maximum: 10 }
  validates :description, presence: true

  def total_price
    total = 0
    recipe_foods.each do |recipe_food|
      total += recipe_food.food.price * recipe_food.quantity
    end
    total
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :inventories, dependent: :destroy
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameter, if: :devise_controller?

  private

  def configure_permitted_parameter
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password)
    end

    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(name: food_params[:name],
                     measurement_unit: food_params[:measurement_unit],
                     price: food_params[:price], user_id: current_user.id)
    if @food.save
      flash[:notice] = 'Food is successfully created'
      redirect_to foods_path
    else
      flash[:notice] = 'Invalid Entry'
      redirect_to new_food_path
    end
  end

  def destroy
    @food = Food.all.find(params[:id]).destroy
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/general_shopping_lists_controller.rb
class GeneralShoppingListsController < ApplicationController
  def index
    @total_items = remaining_foods.length
    @total_amount = total_amount
    @remain_foods = remaining_foods
  end

  private

  def remaining_foods
    total_recipe_foods = []
    current_user.recipes.includes(:recipe_foods).each do |recipe|
      recipe.recipe_foods.includes(:food).each do |recipe_food|
        total_recipe_foods << { name: recipe_food.food.name, quantity: recipe_food.quantity,
                                price: recipe_food.food.price, measurement_unit: recipe_food.food.measurement_unit }
      end
    end
    total_recipe_foods
  end

  def total_amount
    total_amount = 0
    remaining_foods.each do |food|
      total_amount += food[:price] * food[:quantity]
    end
    total_amount
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:recipe_foods).where(public: true).order(id: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @remaining_foods = remaining_foods
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_id: @recipe.id, food_id: recipe_food_params[:food_id],
                                  quantity: recipe_food_params[:quantity])
    if @recipe_food.save
      flash[:notice] = 'Food is successfully added!'
      redirect_to recipe_path(@recipe)
    else
      flash[:notice] = 'Invalid Entry'
      redirect_to current_path
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.all.find(params[:id])
    flash[:notice] = if @recipe_food.destroy
                       'Food Successfully Removed'
                     else
                       'Invalid Transaction'
                     end
    redirect_to recipe_path(@recipe)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end

  def remaining_foods
    total_foods = current_user.foods
    total_recipe_foods = []
    current_user.recipes.includes(:recipe_foods).each do |recipe|
      recipe.recipe_foods.includes(:food).each do |recipe_food|
        total_recipe_foods << recipe_food.food
      end
    end
    total_foods - total_recipe_foods
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes.all
  end

  def show
    @recipes = Recipe.all
    @recipe = @recipes.find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(name: recipe_params[:name], preparation_time: recipe_params[:preparation_time],
                         cooking_time: recipe_params[:cooking_time], user_id: current_user.id,
                         description: recipe_params[:description], public: true)
    if @recipe.save
      flash[:notice] = 'Recipe Successfully Created'
      redirect_to recipes_path
    else
      flash[:notice] = 'Invalid Recipe, all fields have to be completed'
      redirect_to new_recipe_path
    end
  end

  def destroy
    @recipes = Recipe.all
    @recipe = @recipes.find(params[:id])
    if @recipe.destroy
      redirect_to recipes_path
    else
      flash[:notice] = 'Transaction is invalid'
    end
  end

  def update
    Recipe.find(params[:id]).update(public: params[:recipe][:public])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/general_shopping_lists_helper.rb
module GeneralShoppingListsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shoping_helper.rb
module ShopingHelper
end

app/views/foods/_food.html.erb
<div class="food_form_container">
  <%= form_for @food, url: foods_path, method: :post, html: { class: 'foods_form' } do |f| %>
    <%= f.label :name, class: "form_field_label" %>
    <%= f.text_field :name, class: "form_field" %>
    <%= f.label :measurement_unit, class: "form_field_label" %>
    <%= f.text_field :measurement_unit, class: "form_field" %>
    <%= f.label :price, class: "form_field_label" %>
    <%= f.text_field :price, class: "form_field" %>
    <%= f.submit "Submit", class: "food_form_submit_btn" %>
  <% end %>
</div>

app/views/foods/_food_validation_error_message.html.erb
<% if @food.errors.any? %>
  <div style="color: red">
    <h2>
      <%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:
    </h2>
    <ul>
      <% @food.errors.each do |error| %>
      <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/foods/index.html.erb
<div class="add_food_button_container" >
  <%= link_to "Add Food", new_food_path, class: "add_food_btn" %>
</div>
<table class="food_table" >
  <tr>
    <th class="food_heading"><%= t('.food_name') %></th>
    <th class="food_heading"><%= t('.measurement_unit') %></th>
    <th class="food_heading"><%= t('.unit_price') %></th>
    <th class="food_heading"><%= t('.food_action') %></th>
  </tr>
  <% @foods.each_with_index do |food, index| %>
    <tr class="<%= index%2==0 ? 'food_even' : 'food_prime' %>" >
      <td class="food_detail" ><%= food.name %></td>
      <td class="food_detail" ><%= food.measurement_unit %></td>
      <td class="food_detail" >$<%= food.price %></td>
      <td class="food_detail" ><%= button_to "REMOVE", food_path(id: food.id), method: :delete %></td>
    <tr>
  <% end %>
</table>

app/views/foods/new.html.erb
<h1 class="food_form_heading">Add new food</h1>
<%= render "food_validation_error_message" %>
<%= render "food" %>

app/views/general_shopping_lists/index.html.erb
<div class="shopping_list_header">
  <span>
    Total amount to by all items is $<%= @total_amount %>
  </span>
  <span>
    Total items are <%= @total_items %>
  </span>
</div>
<table class="food_table">
  <tr>
    <th class="food_heading"><%= t('.food_name') %></th>
    <th class="food_heading"><%= t('.quantity') %></th>
    <th class="food_heading"><%= t('.total_price') %></th>
  </tr>
  <% @remain_foods.each_with_index do |food, index| %>
    <tr class="<%= index%2==0 ? 'food_even' : 'food_prime' %>" >
      <td class="food_detail" ><%= food[:name] %></td>
      <td class="food_detail" ><%= food[:quantity] %><%= food[:measurement_unit] %></td>
      <td class="food_detail" >$<%= food[:price]*food[:quantity] %></td>
    <tr>
  <% end %>
</table>

app/views/public_recipes/404.html.erb
<div>
  <% content_for :content do %>
    <div style="height: 400px;">
      Can not access this ressource
    </div>
  <% end %>
</div>

app/views/public_recipes/_recipe.html.erb
<div class="recipe mb-2 flex_center py-2">
  <div class="single_recipe d-flex w-100 justify-content-between py-2 px-4">
    <div class="left_block column_direction d-flex justify-content-center align-items-start w-50 px-3">
      <h4 class="fw-bold pb-2"><%= recipe.name %></h4>
      <span class="fs-5">By: <strong><%= recipe.user.name %></strong></span>
    </div>
    <div class="right_block column_direction w-40 d-flex justify-content-center align-items-start">
      <span class="fs-5 pb-2">Total food items: <strong><%= recipe.recipe_foods.length %></span></strong>
      <span class="fs-5 pt-1">Total price: <strong>$<%= recipe.total_price %>.00</strong></span>
    </div>
    <%= link_to 'About Recipe', recipe_path(recipe), class: "line_btn decoration_none align-self-center fs-5 fw-bold" %>
  </div>
</div>

app/views/public_recipes/index.html.erb
<section class="public_recipe_container mt-5">
  <div class="row">
    <% @recipes.each do |recipe| %>
      <%= render partial: "recipe", locals: { recipe: } %>
    <% end %>
  </div>
</section>

app/views/recipe_foods/new.html.erb
<div class="recipe_form_container">
  <%= form_for @recipe_food, url: recipe_recipe_foods_path(@recipe), method: :post, html: { class: 'recipe_form' } do |f| %>
    <%= f.label :quantity, class: "form_field_label" %>
    <%= f.text_field :quantity, class: 'form_field', required: true %>
    <%= f.label :food, class: "form_field_label" %>
    <%= f.collection_select :food_id, @remaining_foods, :id, :name, include_blank: true, class: 'form_field', required: true %>
    <%= f.submit "Submit", class: "recipe_form_submit_btn" %>
  <% end %>
</div>

app/views/recipes/_checkbox.html.erb
<% if can? :read, @recipe %>
  <%= form_with model: @recipe, url: recipe_path(@recipe.id), method: :patch, local: true do |form| %>
    <div class="form-switch">
      <%= form.check_box :public, class: "form-check-input", onchange: 'this.form.submit()' %>
      <%= form.label :Public, 'public', class: "form-check-label", checked: @recipe.public %> <br />
    </div>
  <% end %>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="recipe_form_container">
  <%= form_for @recipe, url: recipes_path, method: :post, html: { class: 'recipe_form' } do |f| %>
    <%= f.label :name, class: "form_field_label" %>
    <%= f.text_field :name, class: 'form_field' %>
    <%= f.label :preparation_time, class: "form_field_label" %>
    <%= f.text_field :preparation_time, class: 'form_field' %>
    <%= f.label :cooking_time, class: "form_field_label" %>
    <%= f.text_field :cooking_time, class: 'form_field' %>
    <%= f.label :description, class: "form_field_label" %>
    <%= f.text_area :description, class: 'form_area_field' %>
    <%= f.submit "Submit", class: "recipe_form_submit_btn" %>
  <% end %>
</div>

app/views/recipes/_recipe_validation_error_message.html.erb
<% if @recipe.errors.any? %>
  <div style="color: red">
    <h2>
      <%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:
    </h2>
    <ul>
      <% @recipe.errors.each do |error| %>
      <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/recipes/index.html.erb
<ul class="recipes_container">
  <% @recipes.each_with_index do |recipe, index| %>
    <li class="recipe_details">
      <%= link_to recipe, class: "recipe_heading" do %>
        <h2 class="recipe_name"><%= recipe.name %></h2>
      <% end %>
        <p class="recipe_description"><%= recipe.description %></p>
        <%= button_to "Remove", recipe_path(id: recipe.id), method: :delete, class: 'remove_recipe_btn' %>
    </li>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<h1 class="recipe_form_heading">Add new recipe</h1>
<%= render "recipe_validation_error_message" %>
<%= render "recipe" %>

app/views/recipes/show.html.erb
<section>
  <ul class="recipe_complete_details_container">
    <li class="recipe_details_head_container">
      <h2><%= @recipe.name %></h2>
      <%= render partial: "checkbox" %>
    </li>
    <li>Preparation Time: <%= @recipe.preparation_time %></li>
    <li>Cooking Time: <%= @recipe.cooking_time %></li>
    <li>Steps are here: <%= @recipe.description %></li>
    <% if can? :destroy, @recipe %>
      <li class="recipe_details_buttons_container">
        <%= link_to "Generate Shopping List", general_shopping_lists_path %>
        <%= link_to "Add Ingredients", new_recipe_recipe_food_path(@recipe) %>
          <%= button_to "Remove Recipe", recipe_path(@recipe), method: :delete %>
      </li>
    <% end %>
    <li>
      <table class="food_table" >
        <tr>
          <th class="food_heading"><%= t('.food_name') %></th>
          <th class="food_heading"><%= t('.quantity') %></th>
          <th class="food_heading"><%= t('.unit_price') %></th>
          <th class="food_heading"><%= t('.action') %></th>
        </tr>
        <% @recipe_foods.includes(:food).each_with_index do |rf, index| %>
          <tr class="<%= index%2==0 ? 'food_even' : 'food_prime' %>" >
            <td class="food_detail" ><%= rf.food.name %></td>
            <td class="food_detail" ><%= rf.quantity %> <%= rf.food.measurement_unit %></td>
            <td class="food_detail" >$<%= rf.food.price %></td>
            <% if can? :destroy, @recipe %>
            <td class="food_detail" ><%= button_to "remove", recipe_recipe_food_path(@recipe, id: rf.id), method: :delete %></td>
            <% end %>
          <tr>
        <% end %>
      </table>
    </li>
  </ul>
</section>